name: documentation

on: [push]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: Update pip
        run: |
          pip install --upgrade pip
          
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser nbsphinx

      - name: Install gensim
        run: pip install --upgrade gensim==4.2.0
        
      - name: Install requirements
        run: python -m pip install -r ./requirements.txt
        
      - name: Sphinx build
        run: |
          docs/make html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
